http:
  port: 9784
  address: "0.0.0.0"

database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456789"
  database: "pulse"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_open_conns: 100
  max_idle_conns: 50
  conn_max_lifetime: 300
  conn_max_idle_time: 60

wecom:
  corp_id: ""                # 在「我的企业」→「企业信息」获取
  corp_secret: ""            # 应用详情页获取
  callback_token: "oKVg17k1qt"
  callback_encoding_aes_key: "1QpUgdLrN4LXmVECb9M2238HowB2v2cQK869Mzxs6Rv"
  agent_id: 0
  sync:
    wiki_id: ""  # 要同步的知识库 ID，为空则同步所有文档

gitops:
  url: "https://git.bilibili.co/tangjingyu/prd.git"
  local_path: "~/DocRepos"
  branch: "main"
  auth:
    type: "http"       # "ssh" 或 "http"
    token: ""          # HTTP Token（type: "http"）
    ssh_key: ""        # SSH 私钥路径（type: "ssh"）
    password: ""       # SSH 私钥密码（type: "ssh"）
